# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Club.create(name: 'Whitby Inter', zone: 'Inter')
Club.create(name: 'Richmond Inter', zone: 'Inter')
Club.create(name: 'Blackwell Grange Inter', zone: 'Inter')
Club.create(name: 'Crook Inter', zone: 'Inter')
Club.create(name: 'Romanby Inter', zone: 'Inter')
Club.create(name: 'Bedale Inter', zone: 'Inter')
Club.create(name: 'Catterick Inter', zone: 'Inter')
Club.create(name: 'Wearside Inter', zone: 'Inter')
Club.create(name: 'Ravensworth Inter', zone: 'Inter')
Club.create(name: 'Roseberry Grange Inter', zone: 'Inter')
Club.create(name: 'Houghton Le Spring Inter', zone: 'Inter')
Club.create(name: 'Parklands Inter', zone: 'Inter')
Club.create(name: 'South Moor Inter', zone: 'Inter')
Club.create(name: 'Hobson Inter', zone: 'Inter')
Club.create(name: 'Stocksfield Inter', zone: 'Inter')
Club.create(name: 'Malton & Norton Inter', zone: 'Inter')
Club.create(name: 'Easingwold Inter', zone: 'Inter')
Club.create(name: 'Darlington Inter', zone: 'Inter')
Club.create(name: 'Ripon City Inter', zone: 'Inter')
Club.create(name: 'Filey Inter', zone: 'Inter')
Club.create(name: 'Kirkbymoorside Inter', zone: 'Inter')
Club.create(name: 'Hunley Hotel& Golf Inter', zone: 'Inter')
Club.create(name: 'Ripon City Rabbits', zone: 'Rabbits')
Club.create(name: 'Dinsdale Spa Rabbits', zone: 'Rabbits')
Club.create(name: 'Filey Rabbits', zone: 'Rabbits')
Club.create(name: 'Romanby Rabbits', zone: 'Rabbits')
Club.create(name: 'Kirkbymoorside Rabbits', zone: 'Rabbits')
Club.create(name: 'Forest Park - York Rabbits', zone: 'Rabbits')
Club.create(name: 'Easingwold Rabbits', zone: 'Rabbits')
Club.create(name: 'Malton & Norton Rabbits', zone: 'Rabbits')
Club.create(name: 'Darlington Rabbits', zone: 'Rabbits')
Club.create(name: 'Richmond Rabbits', zone: 'Rabbits')
Club.create(name: 'Kp Club Rabbits', zone: 'Rabbits')
Club.create(name: 'Whitby Rabbits', zone: 'Rabbits')
Club.create(name: 'Scarborough North Rabbits', zone: 'Rabbits')
Club.create(name: 'Thirsk & Nortallerton Rabbits', zone: 'Rabbits')
Club.create(name: 'Catterick Rabbits', zone: 'Rabbits')
Club.create(name: 'Bedale Rabbits', zone: 'Rabbits')
Club.create(name: 'Boldon Rabbits', zone: 'Rabbits')
Club.create(name: 'Wearside Rabbits', zone: 'Rabbits')
Club.create(name: 'Hobson Rabbits', zone: 'Rabbits')
Club.create(name: 'Billingham Rabbits', zone: 'Rabbits')
Club.create(name: 'Crook Rabbits', zone: 'Rabbits')
Club.create(name: 'Parklands Rabbits', zone: 'Rabbits')
Club.create(name: 'Beamish Rabbits', zone: 'Rabbits')
Club.create(name: 'South Moor Rabbits', zone: 'Rabbits')
Club.create(name: 'Roseberry Grange Rabbits', zone: 'Rabbits')
Club.create(name: 'Seaham Rabbits', zone: 'Rabbits')
Club.create(name: 'Prudhoe Rabbits', zone: 'Rabbits')
Club.create(name: 'Bishop Auckland Rabbits', zone: 'Rabbits')
Club.create(name: 'Houghton Le Spring Rabbits', zone: 'Rabbits')
Club.create(name: 'Chester Le Street Rabbits', zone: 'Rabbits')
Club.create(name: 'Blackwell Grange Rabbits', zone: 'Rabbits')
Club.create(name: 'Garesfield Rabbits', zone: 'Rabbits')
Club.create(name: 'Stocksfield Rabbits', zone: 'Rabbits')
Club.create(name: 'Ravensworth Rabbits', zone: 'Rabbits')
