# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(:email => "abc@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Crook')
User.create(:email => "beamishgolf@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Beamish')
User.create(:email => "glwatts@hotmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Beamish')
User.create(:email => "weighelly@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Bedale')
User.create(:email => "dougnchris@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Bedale')
User.create(:email => "steveyjack@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Bedale')
User.create(:email => "mongon123@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Bedale')
User.create(:email => "jwcturnbull@sky.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Bedale')
User.create(:email => "ajb0497@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Billingham')
User.create(:email => "bcollett18@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Billingham')
User.create(:email => "j.hurst44@ntlworld.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Billingham')
User.create(:email => "dbfletcher87@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Bishop Auckland')
User.create(:email => "mikewalke88@hotmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Blackwell Grange')
User.create(:email => "matt.oakes79@virginmedia.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Blackwell Grange')
User.create(:email => "graham.p61@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Blackwell Grange')
User.create(:email => "info@boldongolfclub.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Boldon')
User.create(:email => "fordm8@sky.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Boldon')
User.create(:email => "kevsolly@googlemail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Catterick')
User.create(:email => "fiveson@ieie.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Catterick')
User.create(:email => "kirkbridejohn@yahoo.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Catterick')
User.create(:email => "gjt270769@yahoo.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Catterick')
User.create(:email => "malcolmpotter@sky.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Chester LS')
User.create(:email => "bobjeanflinn@talktalk.net", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Chester LS')
User.create(:email => "malc63pott@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Chester LS')
User.create(:email => "brianharrison826@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Crook')
User.create(:email => "Malcolm.boughey@yahoo.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Crook')
User.create(:email => "stephen_howarth@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Crook')
User.create(:email => "gamesandhandicap@crookgolfclub.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Crook')
User.create(:email => "Boughey86@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Crook')
User.create(:email => "peterja@talktalk.net", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Crook')
User.create(:email => "e.simpson73@ntlworld.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Darlington')
User.create(:email => "stuartbell74@yahoo.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Darlington')
User.create(:email => "ericgibson_600@fsmail.net", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Dinsdale Spa')
User.create(:email => "mick.a.murphy@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Dinsdale Spa')
User.create(:email => "mikepinder.norton@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Dinsdale Spa')
User.create(:email => "rob.holliday1@sky.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Easingwold')
User.create(:email => "jones.maurice53@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Easingwold')
User.create(:email => "briansteel@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Easingwold')
User.create(:email => "stuart@bucknellwhitehouse.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Easingwold')
User.create(:email => "iantipton4@hotmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Easingwold')
User.create(:email => "paulgroves1978@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Easingwold')
User.create(:email => "paul.gaines@live.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Filey')
User.create(:email => "admin@forestparkgolfclub.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Forest Park')
User.create(:email => "keithandpat@ntlworld.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Forest Park')
User.create(:email => "d.f.keeton@icloud.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Garesfield')
User.create(:email => "rnwarke@hotmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Garesfield')
User.create(:email => "petercpatrick@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Hobson')
User.create(:email => "secretary@hobsongolfclub.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Hobson')
User.create(:email => "douglas.mcdougall@talktalk.net", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Hobson')
User.create(:email => "captain@houghtongolfclub.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Houghton LS')
User.create(:email => "gary.shaw14@me.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Houghton LS')
User.create(:email => "kenneth.musgrove@sky.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Houghton LS')
User.create(:email => "davebryson@ntlworld.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Houghton LS')
User.create(:email => "andyh@hunleyhotel.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Hunley')
User.create(:email => "winspear1@virginmedia.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Hunley')
User.create(:email => "midgley_fred@yahoo.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Kirkbymoorside')
User.create(:email => "p.asquith234@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Kirkbymoorside')
User.create(:email => "richard.ward67@yahoo.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Kirkbymoorside')
User.create(:email => "wkhughes28@yahoo.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Kirkbymoorside')
User.create(:email => "richard@kirkbymoorsidegolf.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Kirkbymoorside')
User.create(:email => "cowiediver@aol.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'KP Club')
User.create(:email => "ashley@thekp.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'KP Club')
User.create(:email => "cdealtry@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'KP Club')
User.create(:email => "gary.tavender@googlemail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'KP Club')
User.create(:email => "tony.ginner@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Malton Norton')
User.create(:email => "mack13@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Malton Norton')
User.create(:email => "melvyn.tindall@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Malton Norton')
User.create(:email => "colinandgill10@sky.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Parklands')
User.create(:email => "tomywatson@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Parklands')
User.create(:email => "cistew4rt@aol.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Parklands')
User.create(:email => "pipsue@tiscali.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Prudhoe')
User.create(:email => "Iroth8@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Prudhoe')
User.create(:email => "raybasson@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Prudhoe')
User.create(:email => "john@ravensworthgolfclub.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Ravensworth')
User.create(:email => "justoon@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Ravensworth')
User.create(:email => "colin.heaney@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Richmond')
User.create(:email => "gordon.dryden@btopenworld.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Richmond')
User.create(:email => "dave.chadwick03@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Richmond')
User.create(:email => "bbarnett44@hotmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Ripon City')
User.create(:email => "waynebest1971@yahoo.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Ripon City')
User.create(:email => "Andrew.c.johnson@talk21.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Ripon City')
User.create(:email => "admin@riponcitygolfclub.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Ripon City')
User.create(:email => "richard_humphrey@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Romanby')
User.create(:email => "PaulFoster0000@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Romanby')
User.create(:email => "roseberrygolf@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Roseberry Grange')
User.create(:email => "rayclif_ford@yahoo.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Roseberry Grange')
User.create(:email => "davidosbornedirectnow@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Roseberry Grange')
User.create(:email => "markhindson78@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Roseberry Grange')
User.create(:email => "cattommy.mb@googlemail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Scarborough')
User.create(:email => "bobarthur16@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Seaham')
User.create(:email => "info@seahamgolfclub.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Seaham')
User.create(:email => "raymond_mccarthy@sky.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'South Moor')
User.create(:email => "ray@albanydrivingschool.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'South Moor')
User.create(:email => "tillydog45@icloud.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Stocksfield')
User.create(:email => "nathanavril@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Stocksfield')
User.create(:email => "bambam663@hotmail.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Thirsk')
User.create(:email => "wendandtrev@yahoo.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Thirsk')
User.create(:email => "robert.picksgill123@btinternet.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Thirsk')
User.create(:email => "derekreveley@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Thirsk')
User.create(:email => "nhojatkinson@hotmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Wearside')
User.create(:email => "g.lydon@btopenworld.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Wearside')
User.create(:email => "pcrawford8819@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Wearside')
User.create(:email => "simonjnewton@yahoo.co.uk", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Wearside')
User.create(:email => "dm.digonpsltd@gmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Whitburn')
User.create(:email => "byronblessed@hotmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Whitby')
User.create(:email => "colinhood2@sky.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Whitby')
User.create(:email => "rutlandcj@hotmail.com", :password => "NERGA2016", :password_confirmation => "NERGA2016", :club => 'Whitby')
User.create(:email => "Matthew@greyhoundit.co.uk", :password => "@NERGA2016", :password_confirmation => "@NERGA2016", :club => 'Admin')
User.create(:email => "iwansliw@yahoo.com ", :password => "IWANNERGA2016", :password_confirmation => "IWANNERGA2016", :club => 'Admin')
